### PR TITLE
Fix missing icalendar_component

### PR DESCRIPTION
**Pull request by e-katkov**
We faced the problem that icalendar_component missing in some cases. Added checks if the event has the icalendar_component attribute.

### CODE REVIEW

**Comment by tobixen** [comment]
That means the server hasn't returned valid data.  Does it work as intended for you with this patch?  Ideally I'd like to have a test case and some credentials to the server for testing, if possible.

In any case, my intention is for the caldav library to be pragmatic and work over as many caldav servers as possible, even when they are breaking the standards, so I will eventually merge this request.

**Comment by tobixen** [comment]
(test failures for 3.7 and 3.8 are due to problems with the testing framework itself, nothing to bother with - I haven't gotten around to look into it yet).

**Comment by e-katkov** [comment]
> That means the server hasn't returned valid data.

We have had "empty" events received in some cases. Such events had VERSION, PRODID, TZID, DTSTART, TZNAME and similar fields. In addition, they did not contain the UID, SUMMARY, DESCRIPTION, ORGANIZER, ATTENDEE, LAST-MODIFIED, RRULE and similar fields.

> Does it work as intended for you with this patch?

Yeah. That's what made it work.

> Ideally I'd like to have a test case and some credentials to the server for testing, if possible.

Unfortunately, that's not possible. We have only gotten this for one user so far. It is not clear how "empty" events are created.

**Comment by tobixen** [comment]
That saves me from spending time doing research on this at least :-)  (may I ask what calendar server it is?)

**Comment by e-katkov** [comment]
Google calendar)

**Comment by e-katkov** [comment]
May I ask when you plan to update version that will have these changes?

**Comment by tobixen** [comment]
sorry that the "worst case" has slipped a bit, hope to get it out soon.

**Pull request merged**
