### PR TITLE
Enable tests of recurring events against Xandikos

### PR DESCRIPTION
**Pull request by jelmer**
Enable tests of recurring events against Xandikos.

### CODE REVIEW

**Comment by tobixen** [comment]
Hurray!

**Comment by tobixen** [comment]
But maybe the test requirement list in setup.py needs to be updated to reflect the minimum version of xandikos to be used?

**Comment by jelmer** [comment]
That's a good point. I'll release a new version this weekend and will send you a pull request to bump the minimum version.

**Comment by tobixen** [comment]
What's the status on this?  I had to reintroduce the incompatibility flags as the tests breaks with 0.2.3 - and 0.2.4 and 0.2.5 breaks even more.

**Comment by jelmer** [comment]
On Wed, Mar 10, 2021 at 02:25:08PM -0800, Tobias Brox wrote:
> What's the status on this?  I had to reintroduce the incompatibility flags as the tests breaks with 0.2.3 - and 0.2.4 and 0.2.5 breaks even more.
This is on my list of things to look at - will hopefully get to it
this week.

Jelmer

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Pull request merged**
