### PR TITLE
Unquote URL path which is matched against property key, which is also…

### PR DESCRIPTION
**Pull request by andrei-mart**
… quoted

Minor optimization of search in a dictionary
ref https://github.com/python-caldav/caldav/issues/11

### CODE REVIEW

**Comment by andrei-mart** [comment]
There is a problem to add a test.
The test would depend on server setup, and test servers are not a part of the test suite.
The environment I tested against uses email addresses as user names, and user name is also a part of base path, and '@' in the key returned from _handle_prop_response() was quoted. I got the error in very basic case: principal.calendars() failed. Current test suite has that call, and I expect it will fail if one of the test environments is set up as mentioned above. It may be enough to create user with name containing @ or # or & or < or > or any other character that should be quoted in URL.

**Comment by tobixen** [comment]
Maybe it's possible to create a calendar with @ in the name?

**Comment by andrei-mart** [comment]
I tried to add @ to IDs, tests pass anyway.
Should it be in the name? 
We want it to appear in the path when a property is returned. I am not familiar with caldav protocol and have no idea how to achieve that.

**Comment by tobixen** [comment]
I'll merge this and look more into it when I get the time.

**Comment by Achimh3011** [comment]
I just ran into this problem after a zimbra upgrade (user is identified by mail address). The PR solves this.

Everything fine, except: when will a new version be released on PyPI? I hate it when I need to reference package dependencies as git repositories...

**Comment by tobixen** [comment]
I hoped to get time to look more into caldav previous week, but ... time is passing so quickly.  I got into some test failures, it seems like one of my caldav test servers is just dropping VTODO items rather than saving them.  Once this issue is fixed I can update the changelog and work on a new release.

**Comment by Achimh3011** [comment]
Thx for the heads-up.

**Pull request merged**
