### PR TITLE
fix: google may return empty ical

### PR DESCRIPTION
**Pull request by zhwei**
something like:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:TEST
X-WR-TIMEZONE:Asia/Shanghai
BEGIN:VTIMEZONE
TZID:Asia/Shanghai
X-LIC-LOCATION:Asia/Shanghai
BEGIN:STANDARD
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
TZNAME:CST
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

### CODE REVIEW

**Comment by tobixen** [comment]
Please use `o.is_loaded()` to check if the object has a payload or not, it's more efficient.

I remember that this issue (google returning empty objects) have been looked into a couple of times, but I don't remember the conclusion.  Will `o.load()` help?

**Comment by tobixen** [comment]
I'm a bit baffled why the tests break.  I'm looking into it.

**Comment by tobixen** [comment]
I do not like the usage of `o.icalendar_component` here, becuase it may involve converting the object into an object from the icalendar library.  Anyway, I can see that it's already used in the same function, after `if kwargs.get("expand", False):`, so then my objection is moot.  :-)  I should probably go over and refactor at a later stage.  It's still needed to figure out why the test breaks though.

**Comment by zhwei** [comment]
@tobixen  Thanks for your review.

> Will o.load() help?

It has no effect, the original data have been loaded, but have no event/todo/etc.

FYI:
this event looks like a event's recurrence item, id format is `idexample001_R20231222@google.com`, i cannot reproduce this event, but my user have 😞 . 
The weird thing is i call `search` with expand=False, this recurrence item should not return standalone. If do not pass sort_keys parameter, the return result is like

```
Event(https://...../idexample001@google.com.ics)
Event(https://...../idexample001_R20231222@google.com.ics)
```

**Comment by tobixen** [comment]
I promised to look into why the test breaks - but then I got interrupted and busy.  I will try and have a look now.

**Comment by tobixen** [comment]
Sorry for overwriting your changes.  I think it will be better this way.  I think the special logic for dealing with objects that aren't loaded or doesn't contain components is not specific to when `expand=True`, and hence it should be outside the if.

I consider this to be a bugfix, as it will cause consistent and expected behaviour even when the caldav server doesn't conform to the RFCs.

**Comment by tobixen** [comment]
Could you confirm that this solves your problems?

**Comment by zhwei** [comment]
@tobixen Yes, it's works for me.

**Pull request merged**
